### ISSUE TITLE
Extending Client Functionality through Plugins

### ISSUE THREAD

**Issue by DamonOehlman** [bigpipe/bigpipe#42]
I notice that the [use](https://github.com/bigpipe/bigpipe#bigpipeuse) section of the docs shows how to write a plugin.  I've had some success writing the `server` handler but so far attempting to implement a `client` handler has yielded no results.

Just wondering if there is some trick to this that I'm missing...

**Comment by 3rd-Eden** [comment]
Closing as it's been fixed in 0.9.x https://github.com/bigpipe/bigpipe-progress/blob/master/index.js is an example of a plugin we use in production.
