### ISSUE TITLE
Assets with no content are created as null.js

### ISSUE THREAD

**Issue by 3rd-Eden** [bigpipe/bigpipe#47]
When you have a pagelet with a completely empty js or css file they will be send as ` {"css":["/null.js"],"js":["/null.js"] }` to the client. These files will also be loading forever since they are not captured by the compiler and for some odd reason the 404 page isn't triggered. 

To reproduce simply load a new Pagelet on an empty page. Set the `css` and `js` to an empty file that you've created using `touch <filename>`

**Comment by 3rd-Eden** [comment]
Stil happening as of today.

**Comment by Swaagie** [comment]
Lol failed reference, anyway https://github.com/bigpipe/bigpipe/commit/0897c2a421758845be5e220b8c67d670d92ee014 will do the following to resolve this issue

- always set content and hash on the file by resolving falsy file content to `''`
- prevent registering an empty file by simply returning if the `!file.length`
- prevent returning undefined aliases and defaulting to `false` in stead of the file path on disk/orginal
- added some compiler tests, \o/

released as 0.9.6, close this issue if you agree on things :)

**Comment by Swaagie** [comment]
Addendum, fittings experienced this issue by fragments being defaulted to `''` which would also not update the file content and hash respectively.

**Comment by 3rd-Eden** [comment]
Fix looks good to me, amazing work sir.
