### ISSUE TITLE
Ability to customize the view used based on request parameters (or similar)

### ISSUE THREAD

**Issue by DamonOehlman** [bigpipe/bigpipe#52]
I'd really like to be able to customise the view used for a page, so that _something like_ the following page configuration would work:

```js
require('../basepage').extend({
  path: '/:org/:role/session/:sessionid',
  view: function() {
    return '../views/session.jade';
  }
}).on(module);
```

In my case, once I had a function that could return which view to use then I would like to configure the view based on the organisation `:org` that was specified.

__NOTE:__ If there is an alternative way of achieving the same outcome, then I'll happily use that instead.

**Comment by 3rd-Eden** [comment]
Closing this as it's not really worth implementing as most template languages that we support already this kind of functionality.
