### ISSUE TITLE
Forego pages, only use pagelets

### ISSUE THREAD

**Issue by Swaagie** [bigpipe/bigpipe#55]
During my last presentation @AmsterdamJS this was suggested by a listener. Based on the frameworks we showed of pages entirely consisting out of pagelets. The driving force behind this change is the ability to have recursive pagelets. If pagelets can act as container, why would pages be required?

This issue could have been created on the [pagelet repo](https://github.com/bigpipe/pagelet) as the biggest changes will be made to that code/repo, however this is more about the general pattern behind bigpipe.

Currently pages are responsible for the following. The question/discussion is where should each part of the logic go? Either shift it to [bigpipe server](https://github.com/bigpipe/bigpipe/blob/master/index.js) or the [pagelet](https://github.com/bigpipe/pagelet).  

**Pagelet discovery**
The pages that are provided to the `Pipe` instance will automatically [discover their pagelets](https://github.com/bigpipe/bigpipe/blob/master/page.js#L903-L921) on initialization. Pagelets already contain the [`traverse`](https://github.com/bigpipe/pagelet/blob/master/index.js#L706-L743) function to discover recursive pagelets, in theory this could be swapped 1:1.

**Rendering**
Pages have logic to accommodate each different rendering mode, e.g. async/pipeline/sync. https://github.com/bigpipe/bigpipe/blob/master/page.js#L297-L396. This logic can be shifted to pagelets.

**Configure/bootstrap html response**
Renders the initial headers and writes the HTML to the client as fast as possible. This is external to pagelets and should move to the bigpipe server. To accommodate request dispatching, the request handling should ideally also be done by the bigpipe server. 

**Request handling**
[Pipe.dispatch](https://github.com/bigpipe/bigpipe/blob/master/index.js#L564-L592) is responsible finding the Page with the correct route and invoking the `Page.configure`. This logic could be shifted to the `Pagelet.configure` method, as long as Pagelets have routing. The [write](https://github.com/bigpipe/bigpipe/blob/master/page.js#L509-L529), [flush](https://github.com/bigpipe/bigpipe/blob/master/page.js#L531-L559) and [end](https://github.com/bigpipe/bigpipe/blob/master/page.js#L458-L507) can be shifted to the bigpipe server. Each pagelet has a reference to the `pipe` instance and should be able to call these methods with the correct data (in stead of referencing this).

**Routing**
Any request is dispatched from bigpipe to responding routes. In stead of the page having a router the pagelet can have a `Router` instance. The tricky part is to ensure this is only done for parent pagelets. When the bigpipe instance calls `optimize` on parent pagelets this should be handled. The parent pagelet will also have to maintain a `params` property. 

**View and dependencies**
Pages and pagelets already both have a view template, this should not matter. In fact by not using a templater (but client side JS, if async render) the amount of template code in templates should be reduced. Since pagelets can simply be included using `<element data-pagelet="name"></element>`

**Charset, status code and content-type**
Should just as easily be contained by the pagelet, the parent pagelet will then determine these, even if a child pagelet has different values. Those child pagelet values shoud be ignored.

**Comment by Swaagie** [comment]
Most bases are covered by the current refactor

**Comment by 3rd-Eden** [comment]
Closing based on comment above as we shipped 0.9 which includes this refactor.
