### ISSUE TITLE
I would like to contribute documentation and examples.

### ISSUE THREAD

**Issue by onesupercoder** [bigpipe/bigpipe#71]
Hello there BigPipe Team,

I would like to contribute documentation and examples.  First I am trying to learn as much as I can from your repositories and issues.  As far as I can tell from using it:  

* Pages are out and nested Pagelets are in.  
* Temper and Primus wrappers for view rendering and realtime connections.
* Over 20 modules that help make bigpipe awesome whose status is available here: https://github.com/bigpipe/bigpipe/blob/master/HEALTH.md

Still have a lot to learn, but would love to help anywhere I can and hopefully you guys can point me in the right direction.  

Also logo, is it a big tobacco pipe?  https://openclipart.org/detail/183205/Pipe  or  a big pipe: https://openclipart.org/detail/204553/Isometric%20pipes

Thanks,
Jared

**Comment by 3rd-Eden** [comment]
@onesupercoder 

We're currently in the process of a complete documentation refactor as we want to move all our documentation to a single Github pages repository so it's easier to maintain and update as the current setup is that great yet. We haven't made that much process on this part yet as we're currently in the process of making BigPipe more modulair. In the 0.9 refactor we already pulled out stuff that doesn't really belong in the "core" of BigPipe as we want to focus making sure that this library only contains the code that is required to correctly and follow the BigPipe pattern as efficient as possible. So more things might still be removed in 0.10.

What we would still love to have are small example apps where people can see what and how you can build apps with this module. We're already discussing building a TodoMVC app: https://github.com/tastejs/todomvc/issues/1161 but anything is more than welcome.

**Comment by 3rd-Eden** [comment]
Oh, and apologies for responding that quickly on IRC ;-) was going to send an e-mail tomorrow but saw this issue popup in my inbox instead.

**Comment by onesupercoder** [comment]
@3rd-Eden that sounds great. :+1:   I was thinking about starting on the github pages repo first because I don't think i would make great example app just yet, but soon.  : ]

**Comment by 3rd-Eden** [comment]
@onesupercoder we were thinking of just using jekyll for it. As that's powerful enough for what we're trying achieve here: 

- Welcome page
- Getting started
- Documentation
- Community
- Blog

**Comment by onesupercoder** [comment]
@3rd-Eden awesome. :+1:  Do you want to make the bigpipe.github.io project and then i will fork it?  Or is there a better way?

**Comment by 3rd-Eden** [comment]
Created https://github.com/bigpipe/bigpipe.github.io/ and deprecated https://github.com/bigpipe/bigpipe.io which currently runs the current bigpipe.io version.

**Comment by 3rd-Eden** [comment]
I think it makes sense to move all documentation site related discussions to that repository.

**Comment by onesupercoder** [comment]
Agreed
